version: "3.8"

services:
    minecraft:
        image: openjdk:17-jdk
        container_name: eterniaserver-container
        build:
            context: .
            dockerfile: ./docker/java/Dockerfile
        restart: "unless-stopped"
        stop_grace_period: "5s"
        ports:
            - "25565:25565"
        volumes:
            - ./src:/usr/src/app
        depends_on:
            - db
        networks:
            - api-network
            - api-proxy-network
        env_file:
            - ./config/.env
    db:
        image: mariadb
        container_name: eterniaserver-mariadb-container
        restart: unless-stopped
        ports:
            - "3305:3305"
        networks:
            - api-network
        env_file:
            - ./config/.env

networks:
    api-proxy-network:
    api-network:
